RecipeApp.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using RecipeApp.Core.Services.Interfaces;

namespace RecipeApp.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryService.GetAllAsync());
        }

        public  async Task<IActionResult> GetCategorywithRecipes(int id) {
            return View(await _categoryService.GetSingleCategoryByIdWithRecipes(id));
        
        }
    }
}

RecipeApp.Web/Controllers/FavoriteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RecipeApp.Core.Repositories.Interfaces;
using RecipeApp.Core.Services.Interfaces;
using RecipeApp.Core.ViewModels.OutViewModels;
using RecipeApp.Service.Services.Objects;
using System.Security.Claims;

namespace RecipeApp.Web.Controllers
{
    [Authorize]
    public class FavoriteController : Controller
    {
        private readonly IFavoriteService _favoriteService;
        private readonly IRecipeService _recipeService;

        public FavoriteController(IFavoriteService favoriteService, IRecipeService recipeService)
        {
            _favoriteService = favoriteService;
            _recipeService = recipeService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _favoriteService.GetAllFavoritesWithRecipe());
        }

        [HttpPost]
        public async Task<IActionResult> AddToFavorites(int recipeId, string userId)
        {
            //TODO: Favorilere eklendiğinde UI'daki Favorilere ekle buton adının değişmesi gerekiyor. 
            //TODO: Favoriler kişiye özel değil. bug
            var recipe = await _recipeService.GetByIdAsync(recipeId);
            var user = userId;
            //TODO burada koşullu yapıyı düzenleyerek daha sade hale getirebilirim. 
            if (recipe == null)
            {
                return NotFound();
            }
            if (User.Identity.IsAuthenticated)
            {
                var favorite = _favoriteService.GetFavoriteWithRecipeAndUser(recipeId , userId);
                if(favorite == null)
                {
                    var favoriteVM = new FavoriteOutVM
                    {
                        RecipeId = recipe.Id,
                        UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                    };
                    var favorites = await _favoriteService.AddAsync(favoriteVM);

                    TempData["Message"] = "Favorilerinize Eklendi!";
                }
                else
                {
                    TempData["Message"] = "Tarif zaten favorilerinizde!";
                }
            }
            //TODO: Şurada favorilerin index'ine değil de recipe controller index'e yönlendirmem lazım.
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Remove(int id)
        {
            var fav =await _favoriteService.GetByIdAsync(id);
            await _favoriteService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

RecipeApp.Web/Controllers/MemberController.cs
using AutoMapper;
using AutoMapper.Execution;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecipeApp.Core.Models;
using RecipeApp.Core.Services.Interfaces;
using RecipeApp.Core.ViewModels;
using RecipeApp.Core.ViewModels.AddViewModel;
using RecipeApp.Core.ViewModels.OutViewModels;
using System.Security.Claims;

namespace RecipeApp.Web.Controllers
{
    [Authorize]
    public class MemberController : Controller
    {
        private readonly SignInManager<User> signInManager;
		private readonly UserManager<User> _userManager;
        private readonly IRecipeService _recipeService;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

		public MemberController(SignInManager<User> signInManager, UserManager<User> userManager, IRecipeService recipeService, ICategoryService categoryService, IMapper mapper)
		{
			this.signInManager = signInManager;
			_userManager = userManager;
			_recipeService = recipeService;
			_categoryService = categoryService;
			_mapper = mapper;
		}

		public IActionResult Index() { 
            return View();
        }
        public async Task<IActionResult> LogOut()
        {
           await signInManager.SignOutAsync();
           return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            // Kullanıcının profil bilgilerini, UserProfileViewModel sınıfı kullanarak oluşturun
            var model = new UserProfileViewModel
			{
				FullName = user.FullName,
				UserName = user.UserName,
				Phone=user.PhoneNumber,
				Email = user.Email,

			};
			return View(model);
		}

        [HttpPost]
        public async Task<IActionResult> Profile(UserProfileViewModel model)
        {
			//Update için

			if (!ModelState.IsValid)
			{
				return View();
			}
			//TODO: Username'i güncelleyince db'de güncelleniyor fakat sonrasında hesabım sayfası açılmıyor
			//çünkü usernamedeğiştiğinde var user = await _userManager.FindByNameAsync(User.Identity.Name); bu satır null geliyor. 
			if (ModelState.IsValid)
			{

				var user = await _userManager.FindByIdAsync(model.Id);
				user.FullName = model.FullName;
				user.Email = model.Email;
                user.PhoneNumber = model.Phone;
				var result = await _userManager.UpdateAsync(user);
				if (result.Succeeded)
				{
					TempData["SuccessMessage"] = "Hesap Bilgileriniz Güncellendi.";
					return RedirectToAction(nameof(Profile));
				}
				
			}

			return View();

		}


		public async Task<IActionResult> Delete(int id)
		{
			var user = await _userManager.FindByNameAsync(User.Identity.Name);
            

			await _userManager.DeleteAsync(user);
            await signInManager.SignOutAsync();

            return RedirectToAction(nameof(Index));

		}


		
    }
}

RecipeApp.Web/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecipeApp.Core.Models;
using RecipeApp.Core.Services.Interfaces;
using RecipeApp.Core.ViewModels.AddViewModel;
using RecipeApp.Core.ViewModels.OutViewModels;
using RecipeApp.Dal.DbContexts;
using System.Security.Claims;

namespace RecipeApp.Web.Controllers
{
    [Authorize]
    public class RecipeController : Controller
    {
        private readonly IRecipeService _recipeService;
		private readonly ICategoryService _categoryService;
        private readonly IFavoriteService _favoriteService;
        private readonly UserManager<User> _userManager;
        public RecipeController(IRecipeService recipeService, AppDbContext appDbContext, ICategoryService categoryService, IFavoriteService favoriteService, UserManager<User> userManager)
        {
            _recipeService = recipeService;
            _categoryService = categoryService;
            _favoriteService = favoriteService;
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index()
        {
           
            return View(await _recipeService.GetAllAsync());
        }

        public async Task<IActionResult> Save()
        {
            var categories = await _categoryService.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(RecipeAddViewModel recipeVM)    
        {
            if (!ModelState.IsValid)
            {
                foreach (var key in ModelState.Keys)
                {
                    var error = ModelState[key].Errors.FirstOrDefault();
                    if (error != null)
                    {
                        var errorMessage = error.ErrorMessage;
                    }
                }
            }

            if (ModelState.IsValid)
            {
                var newMember = new RecipeAddViewModel
                {
                    Name = recipeVM.Name,
                    Description = recipeVM.Description,
                    Ingredients = recipeVM.Ingredients,
                    //TODO: image ekleme??
                    Image = recipeVM.Image,
                    CategoryId = recipeVM.CategoryId,
                    CreatedDate = DateTime.Now,

                    UserId = recipeVM.UserId
                };
                var recipe = await _recipeService.AddAsync(newMember);

                return RedirectToAction(nameof(Index));
            }

            var categories = await _categoryService.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Details(int recipeId)
        {
            var recipe=await _recipeService.GetByIdAsync(recipeId);
            return View(recipe);

        }
    
    }
}

RecipeApp.Web/Views/Shared/NavbarLogin.cshtml
@if (User.Identity.IsAuthenticated)
{
    <ul class="navbar-nav me-0">
        <li class="nav-item dropdown ">
            @*<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                @User.Identity.Name
            </a>*@
            <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" role="button" data-bs-toggle="dropdown" aria-expanded="false"
               href="#"
               id="navbarDropdownMenuLink"
               role="button"
               data-mdb-toggle="dropdown"
               aria-expanded="false">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img (31).webp"
                     class="rounded-circle"
                     height="22"
                     alt="Avatar"
                     loading="lazy" />
            </a>
            <ul class="dropdown-menu dropdown-menu-end px-4 gradient-custom-3"
                aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item " asp-controller="Member" asp-action="LogOut">Çıkış yap</a></li>
                <li><a class="dropdown-item " asp-controller="Member" asp-action="Profile">Hesabım</a></li>

            </ul>
        </li>

    </ul>
}
else
{
    <a class="btn btn-outline-success ms-auto mb-2 mb-lg-0 mx-2" asp-controller="Home" asp-action="SignUp">Kaydol</a>
    <a class="btn btn-outline-success  mx-2" asp-controller="Home" asp-action="SignIn">Giriş Yap</a>
}

RecipeApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipeApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecipeApp.Web.styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/d14c565c21.js"></script>

       <!-- Option 1: Include in HTML -->
  
</head>

<body>
    <header>
        <!-- Sidebar -->
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse gradient-custom-3">

            <div class="position-sticky">

                <div class="list-group list-group-flush mx-3 mt-4 ">

                    <a class="list-group-item list-group-item-action py-2 ripple gradient-custom-3" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Ana sayfa</span>
                    </a>
                    <a class="list-group-item list-group-item-action py-2 ripple gradient-custom-3" asp-controller="Recipe" asp-action="Index">
                        <i class="fas fa-chart-area fa-fw me-3"></i><span>Yemekler</span>
                    </a>
                    <a class="list-group-item list-group-item-action py-2 ripple gradient-custom-3" asp-controller="Recipe" asp-action="Save">
                        <i class="fas fa-chart-area fa-fw me-3"></i><span>Yemek Ekle</span>
                    </a>
                    <a class="list-group-item list-group-item-action py-2 ripple gradient-custom-3" asp-controller="Category" asp-action="Index">
                        <i class="fas fa-chart-area fa-fw me-3"></i><span>Kategoriler</span>
                    </a>
                    <a class="list-group-item list-group-item-action py-2 ripple gradient-custom-3" asp-controller="Favorite" asp-action="Index">
                        <i class="fas fa-chart-area fa-fw me-3"></i><span>Favoriler</span>
                    </a>
                </div>
            </div>
        </nav>
        <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
            <!-- Container wrapper -->
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Yemek Tarifleri</a>
                <!-- Search form -->
                <form class="d-none d-md-flex input-group w-auto my-auto" method="post" asp-action="Search" asp-controller="Home">
                    <input autocomplete="on" type="text" class="form-control rounded" name="SearchString" 
                           placeholder='Search ' style="min-width: 225px;" />
                    <button class="input-group-text border-0  gradient-custom-3"><i class="fa fa-search"></i></button>
                </form>
               
                <partial name="/Views/Shared/NavbarLogin.cshtml" />
            </div>
        </nav>
    </header>
    <main style="margin-top: 58px;">
        <div class="container pt-4"></div>
    </main>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RecipeApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>